algoritmo "Exemplo Repita Até"
// Disciplina  : Algoritmos e Lógica de Programação
// Professor   : Nélio Alves
// Descrição   : Programa para testar o uso do comando "Repita Até" em Portugol. O programa irá solicitar ao usuário que digite um valor e continuará solicitando até que o valor seja "sair".
// Autor(a)    : Bruno Juliano da Silva Corazza
// Data atual  : 16/04/2026
var

C, F : real
resp : caractere

inicio

repita
    escreva("Digite a temperatura em Celsius: ")
    leia(C)
    F <- (C * 9 / 5) + 32
    escreval("Equivalente em Fahrenheit: ", F:6:1)
    escreva("Deseja repetir (s/n)? ")
    leia(resp)
ate resp <> "s"

fimalgoritmo
