algoritmo "Fatorial"
// Disciplina  : Algoritmos e Lógica de Programação
// Professor   : Nélio Alves
// Descrição   : Calcula o fatorial de um número
// Autor(a)    : Bruno Juliano da Silva Corazza
// Data atual  : 14/04/2026
var

N, i, fatorial : inteiro

inicio

escreva("Digite o valor de N: ")
leia(N)

fatorial <- 1

para i de 1 ate N faca 

fatorial <- fatorial * i 

fimpara

escreva("FATORIAL = ", fatorial)

fimalgoritmo